version: 1.0
env: dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_management_system_dev
    username: sankethbolishetti
    password: sanbro2000
  jpa:
    hibernate:
      ddl-auto: update
