version : 2.0
env: prod

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_management_system_prod
    username: sankethbolishetti
    password: sanbro2000
  jpa:
    hibernate:
      ddl-auto: update
